use crate::models::{TargetHost, ScanMetadata};
use super::DataSink;
use anyhow::Result;
use tokio::io::AsyncWriteExt;
use std::path::PathBuf;
use async_trait::async_trait;

/// A DataSink that generates a professional Markdown report.
pub struct MarkdownSink {
    file: tokio::fs::File,
    findings_count: usize,
}

impl MarkdownSink {
    pub async fn new(path: impl Into<PathBuf>) -> Result<Self> {
        let file = tokio::fs::OpenOptions::new()
            .create(true)
            .write(true)
            .truncate(true)
            .open(path.into())
            .await?;
        Ok(Self { file, findings_count: 0 })
    }
}

#[async_trait]
impl DataSink for MarkdownSink {
    async fn write(&mut self, target: &TargetHost) -> Result<()> {
        let mut report = format!("\n## Target: {} (IP: {})\n", target.host, target.ip.as_deref().unwrap_or("Unknown"));
        report.push_str("| ID | Severity | Category | Description |\n");
        report.push_str("|----|----------|----------|-------------|\n");
        
        for f in target.findings.iter() {
            self.findings_count += 1;
            report.push_str(&format!("| {} | **{:?}** | {:?} | {} |\n", f.core.id, f.core.severity, f.core.category, f.core.description));
            
            if let Some(ai) = &f.enrichment.ai_analysis {
                report.push_str(&format!("\n> ### AI Analysis (Model: {})\n", ai.model));
                report.push_str(&format!("> **Summary:** {}\n", ai.summary));
                report.push_str(&format!("> **Impact:** {}\n", ai.impact));
                report.push_str(&format!("> **Exploit Path:** {}\n", ai.exploit_path));
                if let Some(mitre) = &ai.mitre_attack {
                    let mitre_tags: Vec<String> = mitre.iter().map(|s| s.to_string()).collect();
                    report.push_str(&format!("> **MITRE ATT&CK:** {}\n", mitre_tags.join(", ")));
                }
            }
        }
        
        self.file.write_all(report.as_bytes()).await?;
        Ok(())
    }

    async fn write_metadata(&mut self, metadata: &ScanMetadata) -> Result<()> {
        let header = format!("# MIMIKRI - Professional Pentest Report\n\n- **Date:** {}\n- **Command:** `{}`\n\n---\n", 
            chrono::Local::now().format("%Y-%m-%d %H:%M:%S"),
            metadata.command_line);
        self.file.write_all(header.as_bytes()).await?;
        Ok(())
    }

    async fn close(&mut self) -> Result<()> {
        let footer = format!("\n---\n**Total Findings:** {}\n*Generated by Mimikri Sentinel Agent*", self.findings_count);
        self.file.write_all(footer.as_bytes()).await?;
        self.file.flush().await?;
        Ok(())
    }
}
