pub mod report_gen;
pub mod config;
pub mod common;
pub mod liveness;
pub mod telemetry;
pub mod proxy;
pub mod cvss;
pub mod tool_detection;
pub mod memory_monitor;
pub mod jitter;
pub mod process_guard;
pub mod security;
pub mod stealth_detect;
pub mod stealth_http;
pub mod executor;
pub mod payload_server;
pub mod downloader;
pub mod output_filter;

pub use security::{validate_target, is_ssrf_safe_host};
pub use executor::StealthExecutor;
pub use payload_server::PayloadServer;

pub use liveness::LivenessChecker;
pub use report_gen::generate_report;
pub use telemetry::{init_telemetry, shutdown_telemetry};
pub use proxy::ProxyManager;
pub use memory_monitor::MemoryMonitor;
pub use jitter::JitterSleep;
pub use process_guard::ExternalToolGuard;
pub use tool_detection::{detect_tool, detect_tool_system, check_tool_availability, verify_tool_version};
pub mod hardware_detection;
pub use hardware_detection::{InfrastructureType, HardwareInfo, detect_infrastructure};
